name: CI/CD for time-app project

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.19.3']
    
    steps:
      - name: Cloning repsitory
        uses: actions/checkout@v4
      
      - name: Install Node JS ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: API Dependency install
        working-directory: ./api
        run: npm install

      - name: Run unit test
        working-directory: ./api
        run: npm test

      - name: Frontend Dependency install
        working-directory: ./frontend
        run: npm install

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20.19.3']
    
    steps:
      - name: Cloning repsitory
        uses: actions/checkout@v4
      
      - name: Docker login
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      
      - name: API Image build and push to docker hub
        run: |
            docker build -t ${{secrets.DOCKER_USERNAME}}/timeapp-api-1_24_4 ./api
            docker push ${{secrets.DOCKER_USERNAME}}/timeapp-api-1_24_4
      
      - name: FRONT Image build and push to docker hub
        run: |
            docker build -t ${{secrets.DOCKER_USERNAME}}/timeapp-frontend-1_24_4 ./api
            docker push ${{secrets.DOCKER_USERNAME}}/timeapp-frontend-1_24_4
